# Generated by Django 4.2.10 on 2024-11-04 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('content_text', models.CharField(max_length=900000)),
                ('audio', models.FileField(blank=True, null=True, upload_to='audio/')),
            ],
            options={
                'db_table': 'chapters',
            },
        ),
    ]
