# Generated by Django 4.2.10 on 2024-11-05 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book_category',
            old_name='cat',
            new_name='category',
        ),
    ]
